In [5]:
import pandas as pd
import numpy as np

In [6]:
pd.__version__

'2.3.2'

In [23]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [24]:
df.info() # 9704 entries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   engine_displacement  9704 non-null   int64  
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64  
 6   origin               9704 non-null   object 
 7   fuel_type            9704 non-null   object 
 8   drivetrain           9704 non-null   object 
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB


In [25]:
df['fuel_type'].nunique() # two unique fuel types

2

In [26]:
df.isnull().sum() # 4 have missing values

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [27]:
df[df['origin'] == 'Asia'].max() # 23.75

engine_displacement                  370
num_cylinders                       11.0
horsepower                         245.0
vehicle_weight               4661.144932
acceleration                        22.7
model_year                          2023
origin                              Asia
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                            4.0
fuel_efficiency_mpg            23.759123
dtype: object

In [28]:
df_aisa = df[df['origin'] == 'Asia']
df_aisa['fuel_efficiency_mpg'].describe()
# bestätigung von oben 23.75

count    3247.000000
mean       14.973830
std         2.578345
min         6.886245
25%        13.252010
50%        15.034670
75%        16.726318
max        23.759123
Name: fuel_efficiency_mpg, dtype: float64

1. Find the median value of `horsepower` column in the dataset.
2. Next, calculate the most frequent value of the same `horsepower` column.
3. Use `fillna` method to fill the missing values in `horsepower` column with the most frequent value from the previous step.
4. Now, calculate the median value of `horsepower` once again.

In [ ]:
df["horsepower"].median()

149.0

In [35]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [44]:
df[df['horsepower'] == 152] # 142
df_hp = df['horsepower'].fillna(152)

In [ ]:
df_hp.info() # 0 null values

<class 'pandas.core.series.Series'>
RangeIndex: 9704 entries, 0 to 9703
Series name: horsepower
Non-Null Count  Dtype  
--------------  -----  
9704 non-null   float64
dtypes: float64(1)
memory usage: 75.9 KB


In [49]:
df_hp.median() # median increased
df_hp.head()

0    159.0
1     97.0
2     78.0
3    152.0
4    140.0
Name: horsepower, dtype: float64

 Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

- 0.051
- 0.51
- 5.1
- 51


In [50]:
df_aisa = df[df['origin'] == 'Asia']

In [69]:
X = np.array(df_aisa[['vehicle_weight', 'model_year']].head(7))
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [70]:
XTX = X.dot(X.transpose())
XTX


array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [71]:
XTX_INV = np.linalg.inv(XTX)

In [74]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

 Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the resu

In [79]:
dot_product = X.transpose().dot(XTX_INV)
dot_product

array([[ 6.10351562e-04,  1.28173828e-03,  1.22070312e-04,
        -1.95312500e-03, -5.34057617e-04, -1.52587891e-05,
         4.88281250e-04],
       [ 1.22070312e-04, -1.86157227e-03,  7.62939453e-04,
         1.70898438e-03,  3.47137451e-04,  2.97546387e-04,
        -6.40869141e-04]])

In [81]:
w = dot_product * y
w

array([[ 0.67138672,  1.66625977,  0.09765625, -1.7578125 , -0.53405762,
        -0.01678467,  0.5859375 ],
       [ 0.13427734, -2.42004395,  0.61035156,  1.53808594,  0.34713745,
         0.32730103, -0.76904297]])

In [83]:
result = w.sum()
result

np.float64(0.48065185546875)